# raw samples data filename
samples: ""
# table name with format, delimiter, date column name, active cases column name, date format
# Examples:
# 1/22/20: "%m/%d/%y"
# 22-01-2020: "%d-%m-%Y"
# 2020-02-24T18:00:00: "%Y-%m-%dT%H:%M:%S"
reported_cases: ["table.csv",",","date","new_cases","%Y-%m-%d"]
# smooth the reported cases data?
smoothing: False
# Log-transform the estimates for spline computation?
log_transform: True
# metadata filename
samples_meta: ""
# consensus filename
consensus: "sequence"
# number of sequences per bin for binning mode with equally sized bins
number_per_bin: [20,50,100,3500]
# number of days per bin for binning mode with equal amount of calendar days
days_per_bin: [10,15,20]
# minimal bin size - some fraction of big bin file
min_bin_size: 15
# minimal days span
min_days_span: 3
# maximal days span
max_days_span: 21
# Date when e.g. lockdown measures came into place - for plots
date_m: 2020-03-22
# Reported cases full path
rep_cases_full: ""
# Country name for plot grouping
group: ""
# Mode of the run: tree or clusters
mode: "clusters"
# If mode tree - give path to annotated Newick tree with homoplasies and consistency index file
annotated_tree: ""
cindex: ""
